[project]
name = "with-requests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "pytest-playwright>=0.7.1",
    "requests>=2.32.5",
]
